#!/bin/sh
exec <"$0" || exit; read v; read v; exec /usr/bin/osascript - "$@"; exit

set vol to output volume of (get volume settings)
if vol > 90 then # 100 max
  set volume output volume 100
else
  set volume output volume (vol + 10)
end if
