#!/bin/sh
exec <"$0" || exit; read v; read v; exec /usr/bin/osascript - "$@"; exit

set vol to output volume of (get volume settings)
if vol < 10 then # 0 is min
  set volume output volume 0
else
  set volume output volume (vol - 10)
end if
